# Generated by Django 3.2.9 on 2021-11-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbana', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
